import { Vl, om, eG, Qm, xV, m0, aY, jv, rY, sm, zW, IW, LW, DW, PW, rV, PC, Cs, Qb, UW, yG, eV, ri, Yl, VW, rT, Gs, Jj, QW, FW } from '@/lib/reverse-runtime'
let pass = 0, fail = 0
const eq = (n, a, e) => { const x = JSON.stringify(a), y = JSON.stringify(e); if (x === y) pass++; else { fail++; console.log('FAIL ' + n + ': ' + x + ' != ' + y) } }
eq('Vl12', Vl(12), 12); eq('Vl100', Vl(100), 50); eq('Vl-5', Vl(-5), 1)
eq('om_grid', om({grid_no:5},12), 5); eq('om_matched', om({matched_content:'3'},12), 3); eq('om_out', om({matched_content:'20'},12), null)
const m1 = eG([{comment_id:'a',content:'x'},{comment_id:'b',content:'y'}],[{comment_id:'a',content:'z'}])
eq('eG_a', m1.find(i=>i.comment_id==='a').content, 'z'); eq('eG_b', m1.find(i=>i.comment_id==='b').content, 'y')
const qm = Qm([{id:1,nickname:'a'}],[{id:1,nickname:'a2'}],0); eq('Qm_merge', qm[0].nickname, 'a2')
eq('xV_nick', xV({nickname:'小明',itemCode:'A1',buyerNumber:'B2'},'nickname'), '小明')
eq('xV_cargo', xV({nickname:'小明',itemCode:'A1'},'cargoCode'), 'A1')
eq('xV_perm', xV({nickname:'小明',buyerNumber:'B2'},'permanentCode'), 'B2')
eq('m0_id', m0({id:'5',nickname:' 小明 '}).id, 5)
eq('aY', aY('13800000000'), '138****0000')
eq('jv', jv('19.9'), '19.90'); eq('rY', rY(0), '0.00')
eq('eV', eV(new Date('2026-08-01T12:34:56').getTime()), '12:34:56')
eq('ri', ri('1，2, 3'), ['1','2','3']); eq('Yl', Yl('1，2'), '1,2')
eq('yG', yG('小明'), true); eq('yG_mask', yG('张**'), false)
eq('zW', zW.length, 7); eq('IW', IW.length, 2); eq('LW', LW, [4,6,9,12]); eq('DW', DW.length, 5); eq('PW', PW.douyin, 5)
eq('sm', sm.matched.label, '已扣中')
eq('VW', VW('douyin'), true); eq('rT', rT('taobao'), true); eq('Gs', Gs('douyin'), 'dual'); eq('Jj', Jj('wechat_ecosystem'), 'wxstore')
eq('rV_mall', rV({value:'<%=data.mallName%>'},{shop_name:'阳光小铺'}), '阳光小铺')
eq('rV_price', rV({value:'<%=data.price%>'},{price:'19.9'}), '19.9')
eq('rV_content', rV({value:'<%=data.content%>'},{content:'来了'}), '来了')
const uw = UW({printRule:'grid',gridCount:16,numberSpecified:'1，2'})
eq('UW_mode', uw.deductionMode, 'grid'); eq('UW_grid', uw.gridCount, 16); eq('UW_spec', uw.numberSpecified, '1,2')
const pc = PC(); eq('PC_anti', pc.antiDuplicateEnabled, true); eq('PC_grid', pc.gridCount, 12)
eq('QW', QW([1,2,3]).count, 3); eq('FW', FW({comment_id:'c9'}), 'c9')
eq('Cs', Cs().items, [])
console.log(`runtime-helpers: ${pass} pass, ${fail} fail`)
process.exit(fail?1:0)
